# Generated by Django 3.2.7 on 2021-10-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0005_auto_20211020_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(),
        ),
    ]
